### ISSUE TITLE
Pessoas que não estão participando podem jogar.

### ISSUE THREAD

**Issue by JCsound** [kadu/xordroid#36]
![Captura de tela 2021-06-01 222326](https://user-images.githubusercontent.com/66884260/120409788-14ccb400-c328-11eb-9132-ae3633600756.png)

Sem usar o comando "!participar", ele aceita a letra ao invés de apenas dizer para a pessoa usar o comando "!participar".

**Comment by kadu** [comment]
Duplicated #31
